// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package daily

import (
	"server/api/daily"
)

type ControllerV1 struct{}

func NewV1() daily.IDailyV1 {
	return &ControllerV1{}
}