// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package blog

import (
	"server/api/blog"
)

type ControllerV1 struct{}

func NewV1() blog.IBlogV1 {
	return &ControllerV1{}
}
