import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 引入 Arco Design 全局样式，确保组件样式正确呈现
import "@arco-design/web-react/dist/css/arco.css";
// 使用 Client 组件包裹全局 Arco ConfigProvider，避免在 Server Component 中使用 React Context
import ClientProvider from "@/components/ClientProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {/*
          ClientProvider 为客户端组件，内部注入 Arco 的 ConfigProvider。
          保持布局（Server Component）兼容 metadata 等服务端特性。
        */}
        <ClientProvider>
          <Navbar />
          <main style={{ paddingTop: 'var(--navbar-height)' }}>{children}</main>
        </ClientProvider>
      </body>
    </html>
  );
}
