// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// blogArticlesDao is the data access object for the table blog_articles.
// You can define custom methods on it to extend its functionality as needed.
type blogArticlesDao struct {
	*internal.BlogArticlesDao
}

var (
	// BlogArticles is a globally accessible object for table blog_articles operations.
	BlogArticles = blogArticlesDao{internal.NewBlogArticlesDao()}
)

// Add your custom methods and functionality below.
