// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// blogCategoriesDao is the data access object for the table blog_categories.
// You can define custom methods on it to extend its functionality as needed.
type blogCategoriesDao struct {
	*internal.BlogCategoriesDao
}

var (
	// BlogCategories is a globally accessible object for table blog_categories operations.
	BlogCategories = blogCategoriesDao{internal.NewBlogCategoriesDao()}
)

// Add your custom methods and functionality below.
