// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// blogArticleTagsDao is the data access object for the table blog_article_tags.
// You can define custom methods on it to extend its functionality as needed.
type blogArticleTagsDao struct {
	*internal.BlogArticleTagsDao
}

var (
	// BlogArticleTags is a globally accessible object for table blog_article_tags operations.
	BlogArticleTags = blogArticleTagsDao{internal.NewBlogArticleTagsDao()}
)

// Add your custom methods and functionality below.
