// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// blogTagsDao is the data access object for the table blog_tags.
// You can define custom methods on it to extend its functionality as needed.
type blogTagsDao struct {
	*internal.BlogTagsDao
}

var (
	// BlogTags is a globally accessible object for table blog_tags operations.
	BlogTags = blogTagsDao{internal.NewBlogTagsDao()}
)

// Add your custom methods and functionality below.
