// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// blogCommentsDao is the data access object for the table blog_comments.
// You can define custom methods on it to extend its functionality as needed.
type blogCommentsDao struct {
	*internal.BlogCommentsDao
}

var (
	// BlogComments is a globally accessible object for table blog_comments operations.
	BlogComments = blogCommentsDao{internal.NewBlogCommentsDao()}
)

// Add your custom methods and functionality below.
