// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// dynamicConfigsDao is the data access object for the table dynamic_configs.
// You can define custom methods on it to extend its functionality as needed.
type dynamicConfigsDao struct {
	*internal.DynamicConfigsDao
}

var (
	// DynamicConfigs is a globally accessible object for table dynamic_configs operations.
	DynamicConfigs = dynamicConfigsDao{internal.NewDynamicConfigsDao()}
)

// Add your custom methods and functionality below.
