// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// dynamicConfigVersionsDao is the data access object for the table dynamic_config_versions.
// You can define custom methods on it to extend its functionality as needed.
type dynamicConfigVersionsDao struct {
	*internal.DynamicConfigVersionsDao
}

var (
	// DynamicConfigVersions is a globally accessible object for table dynamic_config_versions operations.
	DynamicConfigVersions = dynamicConfigVersionsDao{internal.NewDynamicConfigVersionsDao()}
)

// Add your custom methods and functionality below.
