// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// fileDownloadLogsDao is the data access object for the table file_download_logs.
// You can define custom methods on it to extend its functionality as needed.
type fileDownloadLogsDao struct {
	*internal.FileDownloadLogsDao
}

var (
	// FileDownloadLogs is a globally accessible object for table file_download_logs operations.
	FileDownloadLogs = fileDownloadLogsDao{internal.NewFileDownloadLogsDao()}
)

// Add your custom methods and functionality below.
