// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// logsVisitAccessDao is the data access object for the table logs_visit_access.
// You can define custom methods on it to extend its functionality as needed.
type logsVisitAccessDao struct {
	*internal.LogsVisitAccessDao
}

var (
	// LogsVisitAccess is a globally accessible object for table logs_visit_access operations.
	LogsVisitAccess = logsVisitAccessDao{internal.NewLogsVisitAccessDao()}
)

// Add your custom methods and functionality below.
