// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// weiboAssetsDao is the data access object for the table weibo_assets.
// You can define custom methods on it to extend its functionality as needed.
type weiboAssetsDao struct {
	*internal.WeiboAssetsDao
}

var (
	// WeiboAssets is a globally accessible object for table weibo_assets operations.
	WeiboAssets = weiboAssetsDao{internal.NewWeiboAssetsDao()}
)

// Add your custom methods and functionality below.
