// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// weiboPostsDao is the data access object for the table weibo_posts.
// You can define custom methods on it to extend its functionality as needed.
type weiboPostsDao struct {
	*internal.WeiboPostsDao
}

var (
	// WeiboPosts is a globally accessible object for table weibo_posts operations.
	WeiboPosts = weiboPostsDao{internal.NewWeiboPostsDao()}
)

// Add your custom methods and functionality below.
