// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// weiboSnapshotsDao is the data access object for the table weibo_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type weiboSnapshotsDao struct {
	*internal.WeiboSnapshotsDao
}

var (
	// WeiboSnapshots is a globally accessible object for table weibo_snapshots operations.
	WeiboSnapshots = weiboSnapshotsDao{internal.NewWeiboSnapshotsDao()}
)

// Add your custom methods and functionality below.
